/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},m=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},n=ba(this),q=function(a,b){if(b)a:{var c=n;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];if(!(f in c))break a;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&m(c,a,{configurable:!0,writable:!0,value:b})}};
q("Symbol",function(a){if(a)return a;var b=function(g,e){this.P=g;m(this,"description",{configurable:!0,writable:!0,value:e})};b.prototype.toString=function(){return this.P};var c="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0,f=function(g){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new b(c+(g||"")+"_"+d++,g)};return f});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=n[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&m(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});
var ca=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},v=function(a){return t(a,a)},t=function(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a},w=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},da=function(a){if(!(a instanceof Array)){a=w(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);
a=c}return a},x=function(){this.u=!1;this.l=null;this.i=void 0;this.h=1;this.J=this.S=0;this.s=null},y=function(a){if(a.u)throw new TypeError("Generator is already running");a.u=!0};x.prototype.v=function(a){this.i=a};x.prototype.B=function(a){this.s={T:a,ca:!0};this.h=this.S||this.J};x.prototype.return=function(a){this.s={return:a};this.h=this.J};var z=function(a,b,c){a.h=c;return{value:b}},B=function(a){this.g=new x;this.fa=a};
B.prototype.v=function(a){y(this.g);if(this.g.l)return C(this,this.g.l.next,a,this.g.v);this.g.v(a);return D(this)};var ea=function(a,b){y(a.g);var c=a.g.l;if(c)return C(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return D(a)};B.prototype.B=function(a){y(this.g);if(this.g.l)return C(this,this.g.l["throw"],a,this.g.v);this.g.B(a);return D(this)};
var C=function(a,b,c,d){try{var f=b.call(a.g.l,c);if(!(f instanceof Object))throw new TypeError("Iterator result "+f+" is not an object");if(!f.done)return a.g.u=!1,f;var g=f.value}catch(e){return a.g.l=null,a.g.B(e),D(a)}a.g.l=null;d.call(a.g,g);return D(a)},D=function(a){for(;a.g.h;)try{var b=a.fa(a.g);if(b)return a.g.u=!1,{value:b.value,done:!1}}catch(c){a.g.i=void 0,a.g.B(c)}a.g.u=!1;if(a.g.s){b=a.g.s;a.g.s=null;if(b.ca)throw b.T;return{value:b.return,done:!0}}return{value:void 0,done:!0}},fa=
function(a){this.next=function(b){return a.v(b)};this.throw=function(b){return a.B(b)};this.return=function(b){return ea(a,b)};this[Symbol.iterator]=function(){return this}},ha=function(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,f){function g(e){e.done?d(e.value):Promise.resolve(e.value).then(b,c).then(g,f)}g(a.next())})},E=function(a){return ha(new fa(new B(a)))},ia=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];
return b};
q("Promise",function(a){function b(){this.j=null}function c(e){return e instanceof f?e:new f(function(h){h(e)})}if(a)return a;b.prototype.H=function(e){if(this.j==null){this.j=[];var h=this;this.I(function(){h.U()})}this.j.push(e)};var d=n.setTimeout;b.prototype.I=function(e){d(e,0)};b.prototype.U=function(){for(;this.j&&this.j.length;){var e=this.j;this.j=[];for(var h=0;h<e.length;++h){var k=e[h];e[h]=null;try{k()}catch(l){this.R(l)}}}this.j=null};b.prototype.R=function(e){this.I(function(){throw e;})};
var f=function(e){this.o=0;this.A=void 0;this.m=[];this.M=!1;var h=this.F();try{e(h.resolve,h.reject)}catch(k){h.reject(k)}};f.prototype.F=function(){function e(l){return function(p){k||(k=!0,l.call(h,p))}}var h=this,k=!1;return{resolve:e(this.ha),reject:e(this.G)}};f.prototype.ha=function(e){if(e===this)this.G(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof f)this.ja(e);else{a:switch(typeof e){case "object":var h=e!=null;break a;case "function":h=!0;break a;default:h=!1}h?
this.ga(e):this.K(e)}};f.prototype.ga=function(e){var h=void 0;try{h=e.then}catch(k){this.G(k);return}typeof h=="function"?this.ka(h,e):this.K(e)};f.prototype.G=function(e){this.O(2,e)};f.prototype.K=function(e){this.O(1,e)};f.prototype.O=function(e,h){if(this.o!=0)throw Error("Cannot settle("+e+", "+h+"): Promise already settled in state"+this.o);this.o=e;this.A=h;this.o===2&&this.ia();this.V()};f.prototype.ia=function(){var e=this;d(function(){if(e.da()){var h=n.console;typeof h!=="undefined"&&
h.error(e.A)}},1)};f.prototype.da=function(){if(this.M)return!1;var e=n.CustomEvent,h=n.Event,k=n.dispatchEvent;if(typeof k==="undefined")return!0;typeof e==="function"?e=new e("unhandledrejection",{cancelable:!0}):typeof h==="function"?e=new h("unhandledrejection",{cancelable:!0}):(e=n.document.createEvent("CustomEvent"),e.initCustomEvent("unhandledrejection",!1,!0,e));e.promise=this;e.reason=this.A;return k(e)};f.prototype.V=function(){if(this.m!=null){for(var e=0;e<this.m.length;++e)g.H(this.m[e]);
this.m=null}};var g=new b;f.prototype.ja=function(e){var h=this.F();e.C(h.resolve,h.reject)};f.prototype.ka=function(e,h){var k=this.F();try{e.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};f.prototype.then=function(e,h){function k(u,A){return typeof u=="function"?function(R){try{l(u(R))}catch(S){p(S)}}:A}var l,p,r=new f(function(u,A){l=u;p=A});this.C(k(e,l),k(h,p));return r};f.prototype.catch=function(e){return this.then(void 0,e)};f.prototype.C=function(e,h){function k(){switch(l.o){case 1:e(l.A);
break;case 2:h(l.A);break;default:throw Error("Unexpected state: "+l.o);}}var l=this;this.m==null?g.H(k):this.m.push(k);this.M=!0};f.resolve=c;f.reject=function(e){return new f(function(h,k){k(e)})};f.race=function(e){return new f(function(h,k){for(var l=w(e),p=l.next();!p.done;p=l.next())c(p.value).C(h,k)})};f.all=function(e){var h=w(e),k=h.next();return k.done?c([]):new f(function(l,p){function r(R){return function(S){u[R]=S;A--;A==0&&l(u)}}var u=[],A=0;do u.push(void 0),A++,c(k.value).C(r(u.length-
1),p),k=h.next();while(!k.done)})};return f});q("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var f=d.length;c=c||0;for(c<0&&(c=Math.max(c+f,0));c<f;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}});
q("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return(this+"").indexOf(b,c||0)!==-1}});
var ja=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,f={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};f[Symbol.iterator]=function(){return f};return f};q("Array.prototype.keys",function(a){return a?a:function(){return ja(this,function(b){return b})}});
var F=this||self,ka=function(a,b){a=a.split(".");var c=F;a[0]in c||typeof c.execScript=="undefined"||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||b===void 0?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b},G=function(a){return a};var H=["NONE","ERROR","WARNING","INFO","DEBUG"],la={cep_proxy_url:!0,enable_auto_enrollment:!0,enable_certificate_renewal:!0,allow_machine_cert_enrollment:!0,user_enrollment_templates:!0,device_enrollment_templates:!0,placeholder_values:!0,company_info:!0,log_level:!0,user_cert_request_values:!0,device_cert_request_values:!0,signature_algo:!0,pending_ui_enabled:!0,renew_hours_before_expiry:!0,renew_reminder_interval:!0,request_timeout_seconds:!0,va_api_key:!0,va_enabled:!0,va_google_url:!0,va_shared_secret:!0,
va_request_timeout_seconds:!0,service_account_name:!0,service_account_password:!0,client_authentication:!0,use_key_based_renewal:!0,ces_renewal_url:!0,service_account_host:!0,service_account_host_password_mask:!0},ma=H.indexOf("WARNING"),I=H.indexOf("INFO"),J=H.indexOf("DEBUG"),K=function(a,b){b>0&&b<=J&&b<H.length&&console.log(H[b]+": "+a)},na=function(a){return new Promise(function(b,c){try{chrome.enterprise.platformKeys.getCertificates(a,function(d){chrome.runtime.lastError?c(chrome.runtime.lastError):
b(d)})}catch(d){c(d)}})},L=function(){return new Promise(function(a,b){try{chrome.storage.local.get("ignored_renewal_requests",function(c){c&&c.ignored_renewal_requests?a(c.ignored_renewal_requests):a([])})}catch(c){b(c)}})},oa=function(){var a;E(function(b){if(b.h==1)return z(b,L(),2);a=b.i;a.forEach(function(c){M(N(c))});b.h=0})},pa=function(a){L().then(function(b){b.push(a);chrome.storage.local.set({ignored_renewal_requests:b},function(){})}).then(function(){M(N(a))})},P=function(a){a=O(a);return N(a)},
N=function(a){return"certificate_renewal_alarm:"+a},M=function(a){E(function(b){if(a=="")b.h=0;else return K("Cleaning alarm "+a,J),z(b,chrome.alarms.clear(a),0)})},ra=function(a,b,c){var d,f;E(function(g){if(g.h==1)return z(g,qa(a),2);if(d=g.i)return g.return();f=a.notAfter.value;b>0&&f.setHours(f.getHours()-b);chrome.alarms.create(P(a),{when:f.getTime(),periodInMinutes:c*60});g.h=0})},qa=function(a){var b;return E(function(c){b=P(a);return c.return(new Promise(function(d,f){chrome.alarms.get(b,
function(g){chrome.runtime.lastError?f(chrome.runtime.lastError):d(g!=void 0?!0:!1)})}))})},Q=function(a){var b,c,d,f,g,e,h,k,l,p;return E(function(r){if(r.h==1)return b=null,z(r,L(),2);if(r.h!=3)return c=r.i,c.length>0&&K("The following certificates are explicitly ignored for renewal by the user: "+c.join("\n"),J),z(r,na(a),3);d=r.i;f=w(d);for(g=f.next();!g.done;g=f.next())if(e=g.value,h=window.org.pkijs.fromBER(e),k=new window.org.pkijs.simpl.CERT({schema:h.result}),b==null||b.notAfter.value<k.notAfter.value)c.includes(O(k))||
(b=k);if(!b)return r.return(null);l=new Date;p=b.notAfter.value;return p<l?r.return(null):r.return(b)})},sa=function(a){var b,c,d,f;return E(function(g){if(g.h==1)return b="user",z(g,Q("user"),2);if(g.h!=3)return d=c=g.i,a?z(g,Q("system"),3):d?g.return({slot:b,D:d}):g.return(null);(f=g.i)&&(!c||f.notAfter.value<c.notAfter.value)&&(b="system",d=f);return d?g.return({slot:b,D:d}):g.return(null)})},va=function(){var a=T.allow_machine_cert_enrollment&&T.use_key_based_renewal,b=T.renew_hours_before_expiry?
T.renew_hours_before_expiry:120,c=T.renew_reminder_interval?T.renew_reminder_interval:24,d=ta,f,g;E(function(e){if(e.h==1)return chrome.enterprise?z(e,sa(a),2):e.return();f=e.i;if(!f)return K("No valid certificate found for renewal",J),d!=""&&M(d),e.return();ra(f.D,b,c);a:{if(d!=""){var h=P(f.D);if(d!==h){K("Alarm is not for recent cert",J);h=!1;break a}}h=!0}(g=h)?(K("Valid alaram for renewal notification",J),ua(f.D,b)):(K("Not valid alaram for renewal notification",J),M(d));e.h=0})},ua=function(a,
b){if(wa(a,b))K("Certificate is still valid beyond configured offset.",J);else{K("Certificate will expire before configured offset.",J);a=O(a);b=[];var c={};c.title=chrome.i18n.getMessage("renewal_notification_remind");b.push(c);c={};c.title=chrome.i18n.getMessage("renewal_notification_ignore");b.push(c);chrome.notifications.create(a,{type:"basic",title:chrome.i18n.getMessage("renewal_notification_title"),iconUrl:chrome.runtime.getURL("img/128.png"),message:chrome.i18n.getMessage("renewal_notification_message"),
buttons:b},function(){})}},wa=function(a,b){var c=new Date;return a.notAfter.value.setHours(a.notAfter.value.getHours()-(b===void 0?0:b))>c},O=function(a){return(new Uint8Array(a.serialNumber.value_block.value_hex)).toString()},xa=function(a,b,c){var d,f;return E(function(g){switch(g.h){case 1:if(!a){g.h=2;break}return z(g,Q("system"),3);case 3:return(d=g.i)?g.return(null):b?g.return({slot:"system",method:"kerberos"}):c?g.return({slot:"system",method:"service_account"}):g.return(null);case 2:return z(g,
Q("user"),4);case 4:return(f=g.i)?g.return(null):b?g.return({slot:"user",method:"kerberos"}):g.return(null)}})};var U;/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var ya={};function za(){if(ya!==ya)throw Error("Bad secret");};var V=function(a){za();this.N=a};V.prototype.toString=function(){return this.N+""};function Aa(a){if(U===void 0){var b=null;var c=F.trustedTypes;if(c&&c.createPolicy)try{b=c.createPolicy("goog#html",{createHTML:G,createScript:G,createScriptURL:G})}catch(d){F.console&&F.console.error(d.message)}U=b}b=U;return new V(b?b.createScriptURL(a):a)};var Ba=v([""]),Ca=t(["\x00"],["\\0"]),Da=t(["\n"],["\\n"]),Ea=t(["\x00"],["\\u0000"]),Fa=v([""]),Ga=t(["\x00"],["\\0"]),Ha=t(["\n"],["\\n"]),Ia=t(["\x00"],["\\u0000"]);function W(a){return Object.isFrozen(a)&&Object.isFrozen(a.raw)}function X(a){return a.toString().indexOf("`")===-1}var Ja=X(function(a){return a(Ba)})||X(function(a){return a(Ca)})||X(function(a){return a(Da)})||X(function(a){return a(Ea)}),Ka=W(Fa)&&W(Ga)&&W(Ha)&&W(Ia);var La=function(a){za();this.ea=a};La.prototype.toString=function(){return this.ea};new La("about:blank");new La("about:invalid#zClosurez");var Ma=[],Na=function(a){console.warn("A URL with content '"+a+"' was sanitized away.")};Ma.indexOf(Na)===-1&&Ma.push(Na);function Oa(a){a.importScripts.apply(a,da(ia.apply(1,arguments).map(function(b){if(b instanceof V)b=b.N;else throw Error("Unexpected type when unwrapping TrustedResourceUrl");return b})))};function Pa(a){var b=ia.apply(1,arguments),c=b.length;if(!Array.isArray(a)||!Array.isArray(a.raw)||a.length!==a.raw.length||!Ja&&a===a.raw||!(Ja&&!Ka||W(a))||c+1!==a.length)throw new TypeError("\n    ############################## ERROR ##############################\n\n    It looks like you are trying to call a template tag function (fn`...`)\n    using the normal function syntax (fn(...)), which is not supported.\n\n    The functions in the safevalues library are not designed to be called\n    like normal functions, and doing so invalidates the security guarantees\n    that safevalues provides.\n\n    If you are stuck and not sure how to proceed, please reach out to us\n    instead through:\n     - go/ise-hardening-yaqs (preferred) // LINE-INTERNAL\n     - g/ise-hardening // LINE-INTERNAL\n     - https://github.com/google/safevalues/issues\n\n    ############################## ERROR ##############################");
if(b.length===0)return Aa(a[0]);c=a[0].toLowerCase();if(/^data:/.test(c))throw Error("Data URLs cannot have expressions in the template literal input.");if(/^https:\/\//.test(c)||/^\/\//.test(c)){var d=c.indexOf("//")+2;var f=c.indexOf("/",d);if(f<=d)throw Error("Can't interpolate data in a url's origin, Please make sure to fully specify the origin, terminated with '/'.");d=c.substring(d,f);if(!/^[0-9a-z.:-]+$/i.test(d))throw Error("The origin contains unsupported characters.");if(!/^[^:]*(:[0-9]+)?$/i.test(d))throw Error("Invalid port number.");
if(!/(^|\.)[a-z][^.]*$/i.test(d))throw Error("The top-level domain must start with a letter.");d=!0}else d=!1;if(!d)if(/^\//.test(c))if(c==="/"||c.length>1&&c[1]!=="/"&&c[1]!=="\\")d=!0;else throw Error("The path start in the url is invalid.");else d=!1;if(!(d=d||RegExp("^[^:\\s\\\\/]+/").test(c)))if(/^about:blank/.test(c)){if(c!=="about:blank"&&!/^about:blank#/.test(c))throw Error("The about url is invalid.");d=!0}else d=!1;if(!d)throw Error("Trying to interpolate expressions in an unsupported url format.");
c=a[0];for(d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return Aa(c)};var Qa=v(["background_utils.js"]);self.window===void 0&&ka("window",{});try{Oa(self,Pa(Qa))}catch(a){console.log("Failed to load background_utils due to:",a)}
var Ra=!1,ta="",Sa,Y=function(){try{chrome.storage.onChanged.addListener(this.Y),chrome.runtime.onInstalled.addListener(this.L),chrome.runtime.onMessage.addListener(Ta),chrome.alarms.onAlarm.addListener(this.W),chrome.notifications.onClicked.addListener(this.ba),chrome.notifications.onButtonClicked.addListener(this.aa),chrome.action.onClicked.addListener(this.X),chrome.runtime.onStartup.addListener(this.Z)}catch(a){}this.L({});Ua(function(){va();Va();Ra=!0})};
Y.prototype.Y=function(a,b){K("Handling managed policy change from control panel.",I);if(b=="managed"){var c=T.enable_auto_enrollment,d;for(d in a)T[d]=a[d].newValue;Wa("ccrTabOpenedPreviously",function(f){f=f===void 0||f.ccrTabOpenedPreviously===void 0||!f.ccrTabOpenedPreviously;(c===!1||c===void 0&&f)&&Xa()})}};
var Ta=function(a,b,c){K("Handling request from the frontend.",I);if(b.tab!==void 0)switch(a.action){case "policyRequest":c(JSON.stringify(T));break;case "policyStore":a=JSON.parse(a.data),a!==null&&a!==void 0&&typeof a=="object"&&(T=a)}};Y.prototype.L=function(a){a.OnInstalledReason===void 0?Wa("ccrInstalledPreviously",Ya):Za(a.OnInstalledReason)};Y.prototype.Z=function(){$a();oa()};
Y.prototype.W=function(a){a.name.includes("certificate_renewal_alarm")&&(ta=a.name,K("Certificate renewal alarm triggered.",J),Ra?(K("Extension is active, certificate expirationwill be checked from alarm handling.",J),va(),Va()):(K("Re-creating background worker and checking forexpiring certificates.",J),$a()))};Y.prototype.ba=function(a){a=="ccrAutoEnrollmentNotification"?Z(!1,"auto_provision"):Z(!1,"renewal");chrome.notifications.clear(a)};
Y.prototype.aa=function(a,b){b==1&&(pa(a),K("Ignore certificate renewal request.",I));chrome.notifications.clear(a)};Y.prototype.X=function(){Z(!1,"none")};
var $a=function(){Sa===void 0&&(Sa=new Y)},Wa=function(a,b){chrome.storage!==void 0&&chrome.storage.local.get(a,b)},Ya=function(a){var b="";a!==void 0&&a.ccrInstalledPreviously!==void 0&&a.ccrInstalledPreviously||(b="install",ab("ccrInstalledPreviously"));Za(b)},ab=function(a){var b={};b[a]=!0;chrome.storage.local.set(b,function(){})},Za=function(a){if(a==="install")K("New install detected.",I),Ua(function(){Xa()});else{K("New update detected.",I);var b=T.enable_auto_enrollment;Wa("ccrTabOpenedPreviously",
function(c){Ua(function(){var d=c===void 0||c.ccrTabOpenedPreviously===void 0||!c.ccrTabOpenedPreviously;(b===!1||b===void 0&&d)&&Xa()})})}},Xa=function(){T.enable_auto_enrollment&&Z(!0,"none")},Z=function(a,b){var c="html/request_certificate.html";b!="none"&&(c+="?autoEnrollmentType="+b);b={url:c};a?chrome.tabs.create(b,function(){ab("ccrTabOpenedPreviously")}):chrome.tabs.create(b,function(){})},Ua=function(a){if(chrome.storage&&chrome.storage.managed)try{chrome.storage.managed.get(function(b){if(Object.keys(b).length==
0)K("No managed policy found. Consumer mode.",I);else{K("Managed policy found. Enterprise mode.",I);for(var c in b){var d=b[c];la[c]?T[c]=d:(d=chrome.i18n.getMessage("invalid_policy_var",[c,d.toString()]),K(d,ma))}}a()})}catch(b){}},Va=function(){var a=T.allow_machine_cert_enrollment,b=T.client_authentication==="kerberos",c=bb();xa(a,b,c).then(function(d){d&&chrome.notifications.create("ccrAutoEnrollmentNotification",{type:"basic",title:chrome.i18n.getMessage("auto_enrollment_notification_title"),
iconUrl:chrome.runtime.getURL("img/128.png"),message:chrome.i18n.getMessage("auto_enrollment_notification_message"),requireInteraction:!0},function(){})})},bb=function(){var a=T.service_account_password,b=T.service_account_host;return T.service_account_name&&a||b?T.device_enrollment_templates?!0:(K("No device enrollment templates configured, skipped device auto-enrollment/renewal.",J),!1):(K("No service account configured, skipped device auto-enrollment/renewal.",J),!1)};ka("ccr.background",Y);
var T={};$a();
