# [templates.gtk]
# input_path = '~/.config/matugen/templates/gtk.css'
# output_path = '~/.config/gtk-4.0/colors.css'

[templates.ags]
input_path = '~/.config/matugen/templates/ags.scss'
output_path = '~/.config/ags/style/colors.scss'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'

# [templates.foot]
# input_path = '~/.config/matugen/templates/foot.ini'
# output_path = '~/.config/foot/colors.ini'

[templates.zed]
input_path = '~/.config/matugen/templates/zed.json'
output_path = '~/.config/zed/themes/material-you.json'

[templates.hypr]
input_path = '~/.config/matugen/templates/hypr.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'

# [templates.gtklock]
# input_path = '~/.config/matugen/templates/gtklock.css'
# output_path = '~/.config/gtklock/style.css'

# [templates.yazi]
# input_path = '~/.config/matugen/templates/yazi.toml'
# output_path = '~/.config/yazi/theme.toml'
#
# [templates.zathura]
# input_path = '~/.config/matugen/templates/zathura'
# output_path = '~/.config/zathura/zathurarc'
#
[config]
reload_apps = true
set_wallpaper = true
wallpaper_tool = 'Swww'
prefix = '@'
swww_options = [
    "--transition-type",
    "fade",
    "--transition-step",
    "90",
    "--transition-duration",
    "2",
    "--transition-fps",
    "90",
]

[config.reload_apps_list]
waybar = false
kitty = true
gtk_theme = false
dunst = false

[config.custom_colors]
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
orange = "#fab387"
purple = "#cba6f7"
