# This file is to be overwritten by nwg-displays if you choose to use it.
# nwg-displays is a graphical tool for managing monitors. 
# - Installation for Arch Linux: sudo pacman -S nwg-displays
# - Repo: https://github.com/nwg-piotr/nwg-displays
monitor = DP-1,2560x1440@165,0x0,1
monitor = HDMI-A-1,1920x1080@180,-1920x-80,1
monitor = HDMI-A-2, 1920x1080@120,2560x0,1
workspace = 1, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 5, monitor:DP-1
# Назначения для второго монитора (замените DP-2 на имя вашего монитора)
workspace = 2, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1
workspace = 6,monitor:HDMI-A-1
